### ISSUE TITLE
Adding a pallet switching mechanism.

### ISSUE THREAD

**Issue by hunghvu** [algorithm0r/SuperMarioBros#17]
Color pallet switching is a mechanism used to change a set of color used by a specific sprite. For example, Mario uses a different color pallet when turning into a Fire Mario (not a case in this project as we have a separate sprite for that), or the bricks use different color.

Implement a mechanism so it can change a color pallet of the sprites when it is called.

**Comment by BenjaminDeJager** [comment]
I'm told that "Khue Nguyen, Colin Chan, and Victor Chau" are working on this issue, and wish to be added to this. I can't see them in the assignee's listing however, so I'm adding this comment as a FYI

**Comment by hunghvu** [comment]
I unassign Victor because he's not a part of related PR.
