### ISSUE TITLE
Background music

### ISSUE THREAD

**Issue by BenjaminDeJager** [algorithm0r/SuperMarioBros#19]
determine what background music tracks are in the mario game and add them.

the music might be in a loop, or tied to certain levels--determining this is a part of this issue.

**Comment by BenjaminDeJager** [comment]
Khue Nguyen, Colin Chan, and Victor Chau are working on this issue I'm told, but I don't see their name in the assignee's so I'm adding this post for now.

**Comment by hunghvu** [comment]
This is implemented by Chris in #27. This issue now has become redundant and will be closed.
