### ISSUE TITLE
Adding Mario's sound effects and feed-back

### ISSUE THREAD

**Issue by BenjaminDeJager** [algorithm0r/SuperMarioBros#20]
This is not critically important to the game, but any good game has both sound-effects and audio feed-back to really nail home the game's polish.

since they would be implemented in more-or-less the same way: this issue includes the sound-effects that come from mario interacting with things or taking actions. this issue is for mario's own actions.

Any additional sound effects that need to be implemented to particular enemys (flying, jumping/falling, attacking, etc) will be added later as their importance is not nearly as great as mario's own.

**Comment by BenjaminDeJager** [comment]
I'm told that Khue Nguyen, Colin Chan, and Victor Chau wish to work on this, although they say BGM and pallet-switching are their prioritys.

since I don't see their name(s) in the assignee's list I'm adding this comment.

**Comment by hunghvu** [comment]
As of 2/22/2021, I don't see any PR from them so I will remove them from assignees and change to Chris instead.
