### ISSUE TITLE
merge pirana plant 

### ISSUE THREAD

**Issue by BenjaminDeJager** [algorithm0r/SuperMarioBros#22]
james has already make a pr for their work on the pirana plant and while its been reviewed and accepted, someone still needs to add a few instances to level 1 for testing purposes, and of course do said tests.

I am assigning myself and hung to this issue as our github task includes merge-checking. (FYI for hung, chris has said that if we start getting overwhelmed, we can delegate to relevant persons...but this is not yet true I'd say). 

when it comes to pr-testing, I'd say that if one of us gets it done quickly/easily then great...but if we are struggling we should pm eachother on discord and sort out how/when/who is going to get it done

FYI:
seoungdeok will be making their own pr for the fire bar enemy soon (or possibly sending a link to their fork directly to chris from what I heard, who might just directly push <shrug>) and similar will need to be done for that pr.

**Comment by hunghvu** [comment]
Done
